### PR TITLE
Query component group iterative.

### PR DESCRIPTION
**Pull request by claygoddard**
Add query component grouping iterative support.
Pipe through data and logic to properly handle grouping
when performing iterative requests.

### CODE REVIEW

**Comment by claygoddard** [comment]
Related tests: https://github.com/cowpaths/fs-solr/pull/214

This is the last one that needs to touch Solr internals. The last two components should be much simpler and will only touch our own custom plugins - I'll probably add those laters. No need to push on iterative there yet..

**Comment by noblepaul** [comment]
[optimizeRead.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343136/optimizeRead.patch.txt)
@claygoddard 

I have applied this optimization to all the previous classes as well
[optimizeRead1.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343211/optimizeRead1.patch.txt)


please apply this patch to make deserialization more optimized and clean. We can use this for other object desrializations as well

readObject checks too many types and create a primitive Objects

**Review by chatman — APPROVED** [review]
@noblepaul and I reviewed this and it looks great! +1 to merge.
There are some efficiency improvements to deserialization to consider that Noble attached a patch for; but not a blocker for this.

**Comment by claygoddard** [comment]
> [optimizeRead.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343136/optimizeRead.patch.txt) @claygoddard
> 
> I have applied this optimization to all the previous classes as well [optimizeRead1.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343211/optimizeRead1.patch.txt)
> 
> please apply this patch to make deserialization more optimized and clean. We can use this for other object desrializations as well
> 
> readObject checks too many types and create a primitive Objects

Awesome! I'll apply in a separate PR given the number of changes in the patch and so that I can roll all of the deserialization improvements into one change. Thanks for doing these!

**Comment by claygoddard** [comment]
I just now realized that I hadn't rebased since merging the facet module stuff. Sorry if that threw off the review time. Looks like there were a lot of extra files in here as a result.

**Comment by claygoddard** [comment]
> [optimizeRead.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343136/optimizeRead.patch.txt) @claygoddard
> 
> I have applied this optimization to all the previous classes as well [optimizeRead1.patch.txt](https://github.com/fullstorydev/lucene-solr/files/7343211/optimizeRead1.patch.txt)
> 
> please apply this patch to make deserialization more optimized and clean. We can use this for other object desrializations as well
> 
> readObject checks too many types and create a primitive Objects

Updated readers and writers here: https://github.com/fullstorydev/lucene-solr/pull/111
Thanks for the suggestion and the patches!

**Pull request merged**
