### PR TITLE
Noble/port solr 13661

### PR DESCRIPTION
**Pull request by EmilyBragg**
backport of the plugin hot loading code from SOLR-13661 into solr7_7_1

### CODE REVIEW

**Comment by noblepaul** [comment]
There were some small changes added to the package system I'll merge from master .

**Comment by noblepaul** [comment]
I've ported everything. @chatman do you wish to port the CLI changes as well?

**Comment by chatman** [comment]
I'll update this PR shortly with my CLI changes. Please don't merge yet.

**Comment by chatman** [comment]
@EmilyBragg Please review my last commit, it adds the package manager CLI support. The documentation for usage is here: https://github.com/apache/lucene-solr/blob/master/solr/solr-ref-guide/src/package-manager.adoc

**Comment by noblepaul** [comment]
Good to go

**Pull request merged**
