### PR TITLE
Adding handling of both batched and non-batched updates

### PR DESCRIPTION
**Pull request by justinrsweeney**
Adding handling of both batch and non-batched updates  via the ZkStateWriter, previously non-batched updates would reset specific counters (last updated time and num updates) even though it didn't write all pending updates. Now those will not be reset, allowing pending updates to proceed later.

I've also added an additional test of this logic that failed before these changes and succeeds after these changes.

### CODE REVIEW

**Review by patsonluk — APPROVED** [review]
LGTM! 🎉 

So nice to have extra test cases to verify!
Copied the test case to the `release/8.8` branch, and verified that the `ant test -Dtests.class=org.apache.solr.cloud.overseer.ZkStateWriterTest` failed with 2 errors (expected) and then switching to this branch, re-run the test case and they all passed!

💪🏼

**Comment by noblepaul** [comment]
@justinrsweeney 

That was a very subtle bug that you fixed.  

👍

**Review by noblepaul — APPROVED** [review]

**Review by hiteshk25 — APPROVED** [review]
LGTM

**Comment by patsonluk** [comment]
@hiteshk25 @justinrsweeney @noblepaul 

Also some quick thoughts for improvement in future:

1. Change `writePendingUpdates(Map, boolean)` to `writeUpdates(Map)`  that has no side effects (no reading the field updates nor update counter/timestamp fields), It can just return a boolean on whether the passed in map value was sent
2. Keep the `writePendingUpdates()` signature. Update the counter/timestamp fields here if call to `writeUpdates()` returns true, as this method indeed write pending updates by calling writeUpdates  with the map field `updates`
3. `writeUpdate` will just call the `writeUpdates` with a singleton map

**Comment by justinrsweeney** [comment]
> @hiteshk25 @justinrsweeney @noblepaul
> 
> Also some quick thoughts for improvement in future:
> 
> 1. Change `writePendingUpdates(Map, boolean)` to `writeUpdates(Map)`  that has no side effects (no reading the field updates nor update counter/timestamp fields), It can just return a boolean on whether the passed in map value was sent
> 2. Keep the `writePendingUpdates()` signature. Update the counter/timestamp fields here if call to `writeUpdates()` returns true, as this method indeed write pending updates by calling writeUpdates  with the map field `updates`
> 3. `writeUpdate` will just call the `writeUpdates` with a singleton map

👍 Agreed, this could use more refactoring beyond the quick fix I think. I was thinking even something like carving out writing a single update from the for loop so that PRS could call writing a single update and otherwise it'd write all pending updates. Basically breaking up that method a bit.

**Pull request merged**
