### PR TITLE
Improving the efficiency of create and re-loading replicas

### PR DESCRIPTION
**Pull request by justinrsweeney**
Previously when a replica is reloaded, either on first creation or restart, it would issue a commit to it's leader. In the case of non-leader replicas (i.e. PULL) this is an unnecessary operation since autocommits of the leader should be sufficient. This changes the RecoveryStrategy to skip commit calls to the leader for non leader eligible replicas.

Additionally, previously PULL replicas would repeatedly delete their index and recreate the core every time replication happened until some data was indexed into a leader. This is very inefficient for new collections. This fix checks if the leader and current core are both at their initial version and skips recreating the core if so. Previously this was checking `commit.getGeneration() == 0` but the generation starts at 1 causing the unnecessary operations.

### CODE REVIEW

**Comment by justinrsweeney** [comment]
@noblepaul I'm getting some intermittent failures on FSHATest, curious if you see anything concerning here that could cause that or if that is just flaky: https://app.circleci.com/pipelines/github/cowpaths/fs-solr/1825/workflows/a5818ab9-ab26-45a9-8b3a-09a410f4fed0/jobs/4562

**Comment by noblepaul** [comment]
I'm looking into this @justinrsweeney

**Comment by noblepaul** [comment]
I'm wondering if this is actually supposed to fail once in a while

https://github.com/fullstorydev/lucene-solr/blob/09466e31f4103b2edc742cdf263194a3478b4ee7/solr/core/src/test/org/apache/solr/core/FSHATest.java#L125
there is a random down time of upto 10000ms for the NRT replica

and here it expects the write to succeed within 3000ms 

https://github.com/fullstorydev/lucene-solr/blob/09466e31f4103b2edc742cdf263194a3478b4ee7/solr/core/src/test/org/apache/solr/core/FSHATest.java#L193

@nginthfs can you please confirm this ?

**Comment by justinrsweeney** [comment]
I increased the tolerance for checking how long it takes to route queries to NRT after it is restarted. Tests were occasionally failing due to that, but even retrying the same seed would succeed sometimes. These can be tough in CI I think because any sort of resource contention etc could impact timing here.

**Comment by nginthfs** [comment]
I ran this a couple times locally and not only does that tolerance fail, but sometimes this one does too: https://github.com/fullstorydev/lucene-solr/blob/09466e31f4103b2edc742cdf263194a3478b4ee7/solr/core/src/test/org/apache/solr/core/FSHATest.java#L207

**Review by hiteshk25 — APPROVED** [review]
LGTM (Please create PR against solr-main as well. )

**Pull request merged**
