### PR TITLE
Add log marker to queries in SolrCore

### PR DESCRIPTION
**Pull request by patsonluk**
[ch160298]

## Description
During our practice of assessing and cleaning up our existing Solr log, it's found that GET query can be hidden from the log by default and only enable while debugging

## Solution
Since changing the log verbosity level in code would affect all queries, and using regex filter in config is considered costly, we will add the path of the Solr request as a "marker" to the log, such that we can later on add "Marker Filter" our config to selectively drop log entries for GET query efficiently.

For example, if we want to "hide" GET query, we can add marker filter as below:
```
<Logger name="org.apache.solr.core.SolrCore.Request" level="info">
  <MarkerFilter marker="/get" onMatch="DENY" onMismatch="NEUTRAL"/>
</Logger>
```

### CODE REVIEW

**Comment by noblepaul** [comment]
do we actually use markers anywhere in the logs? or did you change the code to use it? which PR is it?

**Comment by noblepaul** [comment]
LGTM

**Comment by patsonluk** [comment]
> do we actually use markers anywhere in the logs? or did you change the code to use it? which PR is it?

https://github.com/cowpaths/mn/pull/36180/files

**Comment by patsonluk** [comment]
The change was merged in as a part of #102

**Pull request closed without merging**
