### PR TITLE
Rare deadlock on SlotAcc initialization

### PR DESCRIPTION
**Pull request by patsonluk**
## Description
It has been found that a data node has increased amount of threads, and that the stack trace
[thread.txt](https://github.com/fullstorydev/lucene-solr/files/8235913/thread.txt) might indicate deadlock

## Cause
A deadlock is probably formed very similar to what Clay has pointed out http://ternarysearch.blogspot.com/2013/07/static-initialization-deadlock.html .

The core of the issue is that if a parent class reference an instance of its own child class as a static field, a deadlock can be created if 1 thread tries to access the parent class and another thread to the child class.

### Thread A
```
"qtp1393828949-98" #98 prio=5 os_prio=0 cpu=294.10ms elapsed=6252.75s allocated=53246K defined_classes=243 tid=0x00007fa47c007000 nid=0x349c4e in Object.wait()  [0x00007f9896620000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.solr.search.facet.SlotAcc.<clinit>(SlotAcc.java:830)
	at org.apache.solr.search.facet.FacetFieldProcessorByHashDV.createCollectAcc(FacetFieldProcessorByHashDV.java:271)
	at org.apache.solr.search.facet.FacetFieldProcessorByHashDV.calcFacets(FacetFieldProcessorByHashDV.java:255)
```

### Thread B
```
"qtp1393828949-2379" #2379 prio=5 os_prio=0 cpu=34.52ms elapsed=6013.46s allocated=20426K defined_classes=0 tid=0x00007fa49c081800 nid=0x34a58b in Object.wait()  [0x00007f5fcfae7000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.solr.search.facet.FacetFieldProcessorByArray.createCollectAcc(FacetFieldProcessorByArray.java:85)
	at org.apache.solr.search.facet.FacetFieldProcessorByArray.calcFacets(FacetFieldProcessorByArray.java:144)
	at org.apache.solr.search.facet.FacetFieldProcessorByArray.process(FacetFieldProcessorByArray.java:94)
...
```

1. Thread A : FacetFieldProcessorByHashDV.java:271 `indexOrderAcc = new SlotAcc(fcontext) {`, which accesses class `SlotAcc`, it would have a class init lock on `SlotAcc`(assuming first time loading `SlotAcc` in classloader) but BEFORE run to line SlotAcc.java:830
2. Thread B:  FacetFieldProcessorByArray.java:85 `countAcc = new SweepingCountSlotAcc(numSlots, this);`. Accesses `SweepingCountSlotAcc` (also assuming first time loading `SweepingCountSlotAcc` in classloader), loads and initialize based on hierarchy `SweepingCountSlotAcc` -> `CountSlotArrAcc` -> `CountSlotAcc` -> `SlotAcc`, obtain lock and initialize `SweepingCountSlotAcc`,`CountSlotArrAcc`,`CountSlotAcc` but blocked on loading/initializing parent class `SlotAcc`, since Thread A has lock and is already initializing it 
3. Thread A: run to line 830 `static final CountSlotAcc DEV_NULL_SLOT_ACC = new CountSlotAcc(null)...` Found `CountSlotAcc`,  it will attempt to load `CountSlotAcc` as well, but such lock is held by Thread B

With some experiments, class init lock is a bit different from normal object lock and `jstack` cannot seem to detect such deadlocking. However, based on the threads info, it does appear that they are blocking each other.

## Solution
We should break the dependency from `SlotAcc` to `CountSlotAcc` as static field `static final CountSlotAcc DEV_NULL_SLOT_ACC = new CountSlotAcc(null) { ...`

This can be done by moving such field to a new class `SlotAccConstants` which holds `DEV_NULL_SLOT_ACC`, this should break the cyclic dependencies when `SlotAcc` is initialized.

## Remarks
Also reverted a previous attempted fix on `FacetParser` as we now have this new fix.

### CODE REVIEW

**Comment by patsonluk** [comment]
It's a bit hard to reproduce the exact problem with real Solr class. However the test case below shows similar structure (using same class name as Solr to better demonstrate the issue), and can run into deadlock once in a while


```
public class TestInitLock {
  public static void main(String[] args) throws InterruptedException {
    Thread t1 = new Thread() {
      @Override
      public void run() {
        System.out.println("Thread 1");
        System.out.println(new SweepingCountSlotAcc((null)));
      }
    };

    Thread t2 = new Thread() {
      @Override
      public void run() {
        System.out.println("Thread 2");
        System.out.println(SlotAcc.DEV_NULL_SLOT_ACC);
      }
    };

    t1.start();
    t2.start();
    t1.join();
    t2.join();

    System.out.println("Done");
  }
}


class SlotAcc {
  static {
    System.out.println("Loading SlotAcc");
  }
  static final CountSlotAcc DEV_NULL_SLOT_ACC = new CountSlotAcc(null);
}

class CountSlotAcc extends SlotAcc {
  static {
    System.out.println("Loading CountSlotAcc");
  }
  public CountSlotAcc(Object o) {
    super();
  }
}

class SweepingCountSlotAcc extends CountSlotAcc {
  static {
    System.out.println("Loading SweepingCountSlotAcc");
  }
  public SweepingCountSlotAcc(Object o) {
    super(null);
  }
}

```

**Comment by patsonluk** [comment]
Ran unit test cases (`ant test`) on existing `release/8.8` (6 times) and this new branch `patson/slot-acc-deadlock` (5 times)

Here are the failures:

### Release 8.8
RUN 1
   [junit4] Tests with failures [seed: D0B22039D4AC7533]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

RUN 2
   [junit4] Tests with failures [seed: 8666DBBD14916C46]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud
RUN 3
   [junit4] Tests with failures [seed: C76CFBB88DDD39FC]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud
RUN 4
   [junit4] Tests with failures [seed: B73E028772C12BB7]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

RUN 5
   [junit4] Tests with failures [seed: 379183885C231058]:
   [junit4]   - org.apache.solr.metrics.reporters.solr.SolrCloudReportersTest.testDefaultPlugins
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud
…
   [junit4] Tests summary: 929 suites (5 ignored), 4839 tests, 1 error, 1 failure, 258 ignored (212 assumptions)

RUN 6
   [junit4] Tests with failures [seed: BB4BF799F52F219]:
   [junit4]   - org.apache.solr.handler.admin.AutoscalingHistoryHandlerTest.testHistory
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

### patson/slot-acc-deadlock
RUN 1
   [junit4] Tests with failures [seed: 5F6287A288851F43]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

RUN 2
   [junit4] Tests with failures [seed: D7FC715AA26581C6]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud
RUN 3
   [junit4] Tests with failures [seed: AB8DDB5270F14930]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud
   [junit4]   - org.apache.solr.handler.component.CustomHighlightComponentTest (suite)
…
   [junit4] Tests summary: 929 suites (5 ignored), 4838 tests, 1 suite-level error, 1 failure, 247 ignored (211 assumptions)

RUN 4
   [junit4] Tests with failures [seed: D6C2958B95A98951]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

RUN 5
   [junit4] Tests with failures [seed: CC4F7B771B0D6D51]:
   [junit4]   - org.apache.solr.cloud.LegacyCloudClusterPropTest.testCreateCollectionSwitchLegacyCloud

**Comment by noblepaul** [comment]
This looks fine @patsonluk 

However, did we observe any deadlock after the last modification?

**Comment by patsonluk** [comment]
> This looks fine @patsonluk
> 
> However, did we observe any deadlock after the last modification?

It's pretty hard to reproduce it in actual solr, the deadlock is probably a rare case. After all, we only ran into it for one node out of many nodes restarted

**Review by hiteshk25 — APPROVED** [review]
LGTM

**Pull request merged**
