### PR TITLE
Add facet parser factories and plugin support.

### PR DESCRIPTION
**Pull request by claygoddard**
Add facet parser factories and plugin support for adding custom
facet parsers and facet processors.

### CODE REVIEW

**Comment by claygoddard** [comment]
Thoughts here? It'd let us more easily tie into the facet process so that we can take advantage of nested facets and preexisting bucketing (like terms and range). This probably should have been the route we took for our existing search components that produce computations (funnels and journey maps) - I'm going to look into updating them.

**Comment by chatman** [comment]
> Thoughts here? It'd let us more easily tie into the facet process so that we can take advantage of nested facets and preexisting bucketing (like terms and range). This probably should have been the route we took for our existing search components that produce computations (funnels and journey maps) - I'm going to look into updating them.

Is this pluggability support something that we should upstream to Apache Solr so that all we need to do would be to maintain our plugins?

**Comment by claygoddard** [comment]
> > Thoughts here? It'd let us more easily tie into the facet process so that we can take advantage of nested facets and preexisting bucketing (like terms and range). This probably should have been the route we took for our existing search components that produce computations (funnels and journey maps) - I'm going to look into updating them.
> 
> Is this pluggability support something that we should upstream to Apache Solr so that all we need to do would be to maintain our plugins?

Yeah, I think this is totally upstream-able! There may need to be a little thought to how we expose some of the fields / properties of the processor and other related types. But I'm about to put a PR out that shows our funnel computation using it and it feels much nicer than what we were doing with search components and gives us things like dimensionality and substats for free.

**Review by bradbesserman — APPROVED** [review]
LGTM!  

> an take advantage of nested facets and preexisting bucketing

Should be a big performance improvement!

**Comment by claygoddard** [comment]
I'm basically blocking on you here @hiteshk25. So LMK if you have any further questions or concerns!

**Review by hiteshk25 — APPROVED** [review]
LGTM

**Comment by noblepaul** [comment]
The framework looks good. We should be able to upstream this if we can make a sample implementation that is for open source

**Pull request merged**
