### PR TITLE
SOLR-14158: Package trusted keys to come from Package Store, not ZK

### PR DESCRIPTION
**Pull request by chatman**
SOLR-14158: Package trusted keys to come from Package Store, not ZK

Eliminates need for ZK for trusted keys for package manager.

### CODE REVIEW

**Comment by chatman** [comment]
This is based on work by Noble. The upstream PR is here: https://github.com/apache/lucene-solr/pull/1153. If there are changes there, they might need to be ported here.

**Review by noblepaul — APPROVED** [review]
Good to go

**Comment by noblepaul** [comment]
let's hold on this for a while and investigate the test failures

**Comment by noblepaul** [comment]
Test pass. @chatman the only test that is failing is the `PackageManagerCLITest` that fails b/c the version is configured as `8-9` (we have version `7.7`)
This is good to be merged

**Pull request merged**
